### ISSUE TITLE
学习

### ISSUE THREAD

**Issue by xfdywy** [langzhou/siyuan-note#10]
大佬你的两个小挂件看起来很好看，也很好用。感谢。

冒昧问一下，可否开源一下源代码，打包前的，想学习学习~

谢谢~

**Comment by langzhou** [comment]
> 大佬你的两个小挂件看起来很好看，也很好用。感谢。
> 
> 冒昧问一下，可否开源一下源代码，打包前的，想学习学习~
> 
> 谢谢~

ok
