### ISSUE TITLE
删除/撤销文本中评论时不能连带删除文末批注

### ISSUE THREAD

**Issue by zhangxm2312** [langzhou/siyuan-note#13]
希望能够联动文本评论和文末批注。

**Comment by langzhou** [comment]
> 希望能够联动文本评论和文末批注。

@zhangxm2312 建议在评论框中点击移除引文或删除评论。在思源现有机制下，直接删除引文时同步移除文末批注不太好实现，需要监控键盘事件，不过后续得空可以研究下~
