### ISSUE TITLE
评论功能如何加入Tsundoku Green主题？

### ISSUE THREAD

**Issue by WolkeAtreide** [langzhou/siyuan-note#15]
评论和Tsundoku Green都有一个theme.js文件。我尝试吧代码复制到一起，无法生效。

**Comment by langzhou** [comment]
> 评论和Tsundoku Green都有一个theme.js文件。我尝试吧代码复制到一起，无法生效。

将评论theme.js里面的内容复制粘贴到主题 theme.js 文件（不要覆盖原主题 js 内容），记得 comment 文件夹也要一并复制到主题文件夹。

**Comment by WolkeAtreide** [comment]
多谢大佬指点
