### ISSUE TITLE
notes-view公式记忆和图片显示问题及列表视图bug

### ISSUE THREAD

**Issue by WolkeAtreide** [langzhou/siyuan-note#16]
1.公式记忆问题
f5刷新整个文档或者重开软件，公式就会消失，需要重新输入。能否增加一个公式记忆功能？
2.图片显示问题
我尝试过添加题头图，尝试过在链接下方添加图片，都不能在卡片视图中显示出来，这是什么原因？
3.列表视图bug
在可行公式搜索出的结果中，其他视图都能正确跳转到文档，唯独列表视图，所有的块会提示无法找到块的错误，不知原因为何。
![image](https://user-images.githubusercontent.com/101959415/160321248-8a632984-735a-4315-8d39-272dcbab74b3.png)

**Comment by xy0124** [comment]
我刚也提了图片显示bug。卡片视图显示图片是头图。然后头图不管是系统的还是自己上传的，不要进行移动调整操作。不然不显示。

**Comment by WolkeAtreide** [comment]
我这不一样，我这头图都没动过，自定义的，软件自带的都试过，不管用。单纯不显示。
玲，有人和我说必须用iflame，我也试了，与挂件一样。公式倒是记忆了，不过刷新不了，关闭页面再进入什么都不显示。其他的都一样。

**Comment by langzhou** [comment]
这是老版本的挂件，现在思源的相关接口已经变动了。可以等 note-views v2.0版本，还是开发ing....
