### ISSUE TITLE
头图显示bug

### ISSUE THREAD

**Issue by xy0124** [langzhou/siyuan-note#17]
卡片视图下显示头图，发现一个bug，那就是每个文档的头图（系统默认或者自己上传图片），都不能再去进去上下移动调整，只要图片有调整位置，那在卡片视图下就无法显示。
![image](https://user-images.githubusercontent.com/99000021/160340752-a69a1304-892d-48b7-ae3a-fa6a5f463176.png)

**Comment by langzhou** [comment]
note-views v2.0版本应该有做优化，等一等
