### ISSUE TITLE
提一点自己的畅想

### ISSUE THREAD

**Issue by WolkeAtreide** [langzhou/siyuan-note#18]
我有时会用sql来检索一篇文章内的不同标题。这就遇到一个问题，我需要针对每一个标题写出自己的代码，一次次的修改。
是否可以再noteview里加入一个类似标签的效果，可以记住多个公式，让我更快速的检索想要的结果呢？

**Comment by langzhou** [comment]
> 我有时会用sql来检索一篇文章内的不同标题。这就遇到一个问题，我需要针对每一个标题写出自己的代码，一次次的修改。 是否可以再noteview里加入一个类似标签的效果，可以记住多个公式，让我更快速的检索想要的结果呢？

能否具体描述一下问题场景。「我需要针对每一个标题写出自己的代码」这里不是特别理解。

**Comment by WolkeAtreide** [comment]
我设置一个双链汇总页面，叫美剧。好，我写好公式，把所有汇总到这个页面，完成。
那，美剧又分很多，《犯罪心理》《基本演绎法》，今天我突然想看关于犯罪心理的笔记。我需要重新写公式，把标题中带有犯罪心理字样的筛选出来。看完以后再把公式恢复到原来的。
如果一周以后我又想看犯罪心理相关的笔记呢？我又要把公式重新写一遍。如果加入一个标签功能，我点击一下标签，noteview自动就加载犯罪心理的公式，也就不需要每次都重复操作。

**Comment by WolkeAtreide** [comment]
或者，做成像notion的标签筛选？自己加进属性，然后加进筛选条件，自动筛选

**Comment by langzhou** [comment]
> 或者，做成像notion的标签筛选？自己加进属性，然后加进筛选条件，自动筛选

标签筛选可以实现。但相比 notion 而言，会弱很多。

**Comment by WolkeAtreide** [comment]
肯定不能和notion比，只要能记忆常用的几个公式我觉得就完全够用了。
