### ISSUE TITLE
1.9.6以后，comment失效了

### ISSUE THREAD

**Issue by WolkeAtreide** [langzhou/siyuan-note#22]
![zhangdark](https://user-images.githubusercontent.com/101959415/161364892-50c93c45-fa64-497b-b925-7c5f956e87b3.png)
![green](https://user-images.githubusercontent.com/101959415/161364896-399f6967-0179-43d3-b058-feaf8f8c4994.png)
![zhangliang](https://user-images.githubusercontent.com/101959415/161364898-8deafd7d-3da9-4be6-b54a-76800570d233.png)

**Comment by langzhou** [comment]
> ![zhangdark](https://user-images.githubusercontent.com/101959415/161364892-50c93c45-fa64-497b-b925-7c5f956e87b3.png) ![green](https://user-images.githubusercontent.com/101959415/161364896-399f6967-0179-43d3-b058-feaf8f8c4994.png) ![zhangliang](https://user-images.githubusercontent.com/101959415/161364898-8deafd7d-3da9-4be6-b54a-76800570d233.png)

如果是手动添加的 comment，更新主题后主题的 theme.js会覆盖之前的。试着把 comment 里的 theme.js重新放置到主题文件夹呢？

**Comment by WolkeAtreide** [comment]
zhangdark和zhangliang主题没有theme.js，不会导致覆盖问题。日语主题有这个问题，我也重新操作过了，没有唤醒。。

**Comment by langzhou** [comment]
> zhangdark和zhangliang主题没有theme.js，不会导致覆盖问题。日语主题有这个问题，我也重新操作过了，没有唤醒。。

可以打开开发者工具，看看有没有报错

**Comment by WolkeAtreide** [comment]
emmm，挂件没生效也能用开发者工具么？

**Comment by langzhou** [comment]
> emmm，挂件没生效也能用开发者工具么？

嗯，可能是 js 加载出错了，看看开发者工具里有没有异常报错

**Comment by WolkeAtreide** [comment]
> > emmm，挂件没生效也能用开发者工具么？
> 
> 嗯，可能是 js 加载出错了，看看开发者工具里有没有异常报错

看这样也没啥。我重新下载了覆盖也不管用。

![image](https://user-images.githubusercontent.com/101959415/161501184-dc65b034-c5ee-4413-a030-590be35d9bfb.png)

**Comment by WolkeAtreide** [comment]
> > emmm，挂件没生效也能用开发者工具么？
> 
> 嗯，可能是 js 加载出错了，看看开发者工具里有没有异常报错

我用的是zhanglight，内置的这个功能。大概是只有我这不能用吧。

**Comment by langzhou** [comment]
> > > emmm，挂件没生效也能用开发者工具么？
> > 
> > 
> > 嗯，可能是 js 加载出错了，看看开发者工具里有没有异常报错
> 
> 我用的是zhanglight，内置的这个功能。大概是只有我这不能用吧。

这个暂时就不太清楚了😭
