### ISSUE TITLE
Docker 部署 Note Attrs 和 Note Views v3 无法查询

### ISSUE THREAD

**Issue by Skywt2003** [langzhou/siyuan-note#26]
Docker 部署思源，使用 Note Attrs 和 Note Views v3 挂件，均无法查询到数据，显示错误：「网络请求错误 [set_block_attrs]：Failed to fetch」「查询结果为空 | 未检索到子文档」。选择「自定义 SQL」后输入有效的 SQL 语句，也得到一样的错误。

在其他条件相同的情况下，在 **Docker 部署**和**本地运行**两种环境进行测试，后者均可以正常查询，前者均出现此错误。

尝试重建索引、重启思源或 Docker 容器等，均一直有此错误。

Docker 部署环境下，使用「Query」挂件可以正常查询 SQL。感觉不是思源的问题。

<img width="1440" alt="截屏2022-05-13 下午3 34 00" src="https://user-images.githubusercontent.com/29029278/168234160-fe22be5f-5a9f-47af-b1a6-f7022a4a093c.png">

**Comment by langzhou** [comment]
安装 Note Attrs v1.2.1也有这个问题么？

**Comment by Skywt2003** [comment]
我是 Note Attrs v1.3.0，仍然有这个问题……

F12 看了一下确实是 https 的问题。

<img width="1440" alt="截屏2022-05-13 下午3 58 15" src="https://user-images.githubusercontent.com/29029278/168238104-aa3c6e66-61ad-41ee-8a6c-1fdd198bf9f7.png">

**Comment by langzhou** [comment]
> 我是 Note Attrs v1.3.0，仍然有这个问题……
> 
> F12 看了一下确实是 https 的问题。
> 
> <img alt="截屏2022-05-13 下午3 58 15" width="1440" src="https://user-images.githubusercontent.com/29029278/168238104-aa3c6e66-61ad-41ee-8a6c-1fdd198bf9f7.png">

截图一个 note attrs 的图看看，你这个是 note views 的

**Comment by Skywt2003** [comment]
Note Attrs 1.3.0 没问题 🌝 只有 Note Views 有问题

**Comment by Skywt2003** [comment]
用 Chrome 访问的时候 Note Attrs 没问题，我用 Nativefier 把网页打包成应用使用（也是基于 Election），Note Attrs 就也会有问题 😵‍💫 可能是 Chromium 版本问题？

<img width="1440" alt="截屏2022-05-13 下午6 25 51" src="https://user-images.githubusercontent.com/29029278/168265023-ed9c848e-ac93-4d94-92e6-bdd746bd3f9c.png">

**Comment by langzhou** [comment]
嗯，下午更新了 2 个挂件，等后面集市里更新下再试试

**Comment by Skywt2003** [comment]
更新之后可以了！！感谢大佬！！
