### ISSUE TITLE
毛玻璃下，2个错位的feedback

### ISSUE THREAD

**Issue by Morganwan90** [langzhou/siyuan-note#3]
大佬好，刚开始学习css，从你和VIWZ的主题中学习摸索。
反馈2个错位的feedback：
开启毛玻璃模式下，会导致1、搜索框中出来的文本和2、链接打开的浮窗中文本的段落标识错位，如图：
![截图_20212701042717](https://user-images.githubusercontent.com/61633409/127764612-b16a37bf-2d0b-41b7-aaac-b3bf0bae450d.png)
![截图_20212601042640](https://user-images.githubusercontent.com/61633409/127764592-5da32a64-8798-4430-b885-053195586cb2.png)

我自己瞎捯饬了一下，发现.block__popover和.b3-dialog__containe不能直接用backdrop-filter，还是要先设置一个背景图片再叠加一个背景色就正常了...
我不知道我有没有说明白..我就是纯摸索...不是专业人士..

**Comment by langzhou** [comment]
@Morganwan90  是在 winter-mix 下的错位么，还是 toy？毛玻璃特效我也是第一次尝试，边学边用，也还在摸索。

**Comment by Morganwan90** [comment]
> @Morganwan90  是在 winter-mix 下的错位么，还是 toy？毛玻璃特效我也是第一次尝试，边学边用，也还在摸索。
如果在toy里面把毛玻璃那段代码启动也是一样出现（默认是木有开，winter-mix是默认开的），没开就不影响。

**Comment by langzhou** [comment]
@Morganwan90 嗯。我记得最开始的时候也遇到过这个不知原因的块标错误。需要进一步看看是什么原因导致的。

**Comment by Morganwan90** [comment]
> @Morganwan90 嗯。我记得最开始的时候也遇到过这个不知原因的块标错位。需要进一步看看是什么原因导致的。

我昨天摸索了然后弄成功了，就是不能直接用backdrop-filter，涉及的就是.block__popover和.b3-dialog__containe。
我把他改成下面那样的就好了...好像就是主编辑区那个是设置了背景图片所以可以直接用backdrop-filter，对于浮窗和设置这些弹出来的窗口，就要再重新设置一个背景图片，再用另一个背景去backdrop-filter。

![截图_20214501114546](https://user-images.githubusercontent.com/61633409/127777069-69e2f7ef-dcb5-4055-9462-c8f3cce378b4.png)

![截图_20214701114707](https://user-images.githubusercontent.com/61633409/127777108-d00fb3dc-22f4-45d0-97b9-a580db687cd1.png)

**Comment by langzhou** [comment]
> > @Morganwan90 嗯。我记得最开始的时候也遇到过这个不知原因的块标错位。需要进一步看看是什么原因导致的。
> 
> 我昨天摸索了然后弄成功了，就是不能直接用backdrop-filter，涉及的就是.block__popover和.b3-dialog__containe。
> 我把他改成下面那样的就好了...好像就是主编辑区那个是设置了背景图片所以可以直接用backdrop-filter，对于浮窗和设置这些弹出来的窗口，就要再重新设置一个背景图片，再用另一个背景去backdrop-filter。
> 
> ![截图_20214501114546](https://user-images.githubusercontent.com/61633409/127777069-69e2f7ef-dcb5-4055-9462-c8f3cce378b4.png)
> 
> ![截图_20214701114707](https://user-images.githubusercontent.com/61633409/127777108-d00fb3dc-22f4-45d0-97b9-a580db687cd1.png)

嗯嗯👍🏻
