### ISSUE TITLE
无法使用comment插件

### ISSUE THREAD

**Issue by LBDOC** [langzhou/siyuan-note#33]
langzhou老师好，我的思源版本是2.10.10，您的评论插件非常好，完全契合了我想阅读文章的时候撰写某句话某个段落感悟的想法。我下载了github里面siyuan-comment的文件，将js文件和comment文件夹复制到主题文件夹下面，但是在很多主题里面都没有成功，在选中文字后，toolbar没有看到“评论”那个按钮。

由于dark+内置了你的插件，所以使用dark+可以使用。我很想用这个功能，想请问一下是什么原因？

**Comment by langzhou** [comment]
@LBDOC 好，这个挂件很久没有维护了，所以估计会和当前思源笔记版本或主题存在兼容的问题。建议使用集成了评论插件功能的主题~
