### ISSUE TITLE
NoteView 自定义SQL

### ISSUE THREAD

**Issue by Crowds21** [langzhou/siyuan-note#4]
## 块属性
下列属性后续是否会支持自定义呢?
![image](https://user-images.githubusercontent.com/48215334/128375276-f94c46ce-36de-4085-9938-4e542994e703.png)
![image](https://user-images.githubusercontent.com/48215334/128375438-286b2dbd-637b-4918-9e94-753f61c75b43.png)

## 自定义SQL
貌似无法进行跨笔记本的搜索, 这个是和设计逻辑或现阶段没有API有关系吗,后续是否也会实现呢?

**Comment by Crowds21** [comment]
贪心一点,还希望能有个像github一样的热力图😀

**Comment by langzhou** [comment]
@Crowds21 

1. 跨笔记本搜索应该是支持的，需要自定义 SQL，例如`select * from blocks where box = '笔记本名称'`
2. 自定义属性这个可能得等官方挂件集市正式上线后再考虑，目前的挂件只是做一个前期的探索性尝试
3. 热力图好像有其他网友已经实现了哈

**Comment by Crowds21** [comment]
> @Crowds21
> 
> 1. 跨笔记本搜索应该是支持的，需要自定义 SQL，例如`select * from blocks where box = '笔记本名称'`
> 2. 自定义属性这个可能得等官方挂件集市正式上线后再考虑，目前的挂件只是做一个前期的探索性尝试
> 3. 热力图好像有其他网友已经实现了哈

单词拼错,是我闹乌龙了.hhhh.
